
server:
  port: 8082

spring:
  application:
    name: milk-service
  datasource:
    url: jdbc:mysql://localhost:3306/cow_db
    username: root
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
