server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: cow-service
          uri: lb://cow-service
          predicates:
            - Path=/cows/**
        - id: insurance-service
          uri: lb://insurance-service
          predicates:
            - Path=/insurance/**

  discovery:
    locator:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka