server.port=8080

spring.application.name=gateway-service
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.routes[0].id=cow-service
spring.cloud.gateway.routes[0].uri=lb://cow-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/cows/**
spring.cloud.gateway.routes[1].id=insurance-service
spring.cloud.gateway.routes[1].uri=lb://insurance-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/insurance/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
