version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cow_db
    ports:
      - "3306:3306"

  discovery-service:
    build: ../discovery-service
    ports:
      - "8761:8761"

  gateway-service:
    build: ../gateway-service
    ports:
      - "8080:8080"

  cow-service:
    build: ../cow-service
    ports:
      - "8081:8081"
